apiVersion: apps/v1
kind: Deployment
metadata:
  name: people-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: people-api
  template:
    metadata:
      labels:
        app: people-api
    spec:
      containers:
        - name: people-api
          image: fabianogoes/people-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 1m
          envFrom:
            - secretRef:
                name: app-secret
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_HOST
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_DB
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: TOKEN_SECRET
            - name: DB_PORT
              value: "5432"
            - name: APP_ENV
              value: "production"
            - name: APP_PORT
              value: ":8080"
            - name: API_VERSION
              value: "2024.5.1.5"
      restartPolicy: Always

